version: 0.0
os: linux
files:
  - source:  /
    destination: /home/ubuntu/build/

permissions:
  - object: /
    pattern: "**"
    mode: '755'
    owner: root
    group: root

hooks:
#  BeforeInstall:
#    - location: stop.sh
#      runas: root
#  ApplicationStart:
#    - location: start.sh
#      runas: root